### ISSUE TITLE
Enabling system assertions fails

### ISSUE THREAD

**Issue by farquet** [dacapobench/dacapobench#163]
The harness fails if all assertions are enabled.

Reproducer : `java -esa -jar dacapo-9.12-MR1-bach.jar sunflow -n 2`

```
Using scaled threading model. 12 processors detected, 12 threads used to drive the workload, in a possible range of [1,256]
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.dacapo.harness.Sunflow.preIteration(Sunflow.java:52)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:171)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Harness.main(Unknown Source)
Caused by: java.lang.AssertionError: Exception raised while reading logging configuration: java.security.PrivilegedActionException: java.io.FileNotFoundException: ./scratch/sunflow.log (No such file or directory)
	at java.util.logging.LogManager.readPrimordialConfiguration(LogManager.java:407)
	at java.util.logging.LogManager.access$800(LogManager.java:145)
	at java.util.logging.LogManager$2.run(LogManager.java:345)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.ensureLogManagerInitialized(LogManager.java:338)
	at java.util.logging.LogManager.getLogManager(LogManager.java:378)
	at java.util.logging.Logger.getPlatformLogger(Logger.java:572)
	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:602)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.<init>(PlatformLogger.java:597)
	at sun.util.logging.PlatformLogger.<init>(PlatformLogger.java:239)
	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:198)
	at sun.awt.AppContext.<clinit>(AppContext.java:136)
	at javax.imageio.spi.IIORegistry.getDefaultInstance(IIORegistry.java:154)
	at javax.imageio.ImageIO.<clinit>(ImageIO.java:66)
	at org.sunflow.Benchmark.<init>(Benchmark.java:91)
	... 13 more
```

This is most likely due to this system property being set : https://github.com/dacapobench/dacapobench/blob/master/benchmarks/harness/src/org/dacapo/harness/Benchmark.java#L222
It's possible to work around the problem by disabling assertions for `java.util.logging` : 
`java -esa -da:java.util.logging... -jar dacapo-9.12-MR1-bach.jar sunflow -n 2`

**Comment by steveblackburn** [comment]
Fixed in 5e74537e
