### ISSUE TITLE
cassandra fails on some OpenJDK 13 builds

### ISSUE THREAD

**Issue by shipilev** [dacapobench/dacapobench#172]
Again, using my own bleeding edge builds:

```
$ jdk11/bin/java -version
openjdk version "11.0.4-testing" 2019-07-16
OpenJDK Runtime Environment (fastdebug build 11.0.4-testing+0-builds.shipilev.net-openjdk-jdk11-b140-20190620-jdk-11.0.48)
OpenJDK 64-Bit Server VM (fastdebug build 11.0.4-testing+0-builds.shipilev.net-openjdk-jdk11-b140-20190620-jdk-11.0.48, mixed mode)

$ jdk13/bin/java -version
openjdk version "13-testing" 2019-09-17
OpenJDK Runtime Environment (fastdebug build 13-testing+0-builds.shipilev.net-openjdk-jdk13-b11-20190623-jdk-1326)
OpenJDK 64-Bit Server VM (fastdebug build 13-testing+0-builds.shipilev.net-openjdk-jdk13-b11-20190623-jdk-1326, mixed mode, sharing)
```
Cassandra fails to run:

```
$ jdk13/bin/java -jar dacapo-evaluation-git+8b7a2dc.jar -n 5 cassandra
Cassandra starting...
...
Caused by: java.lang.NumberFormatException: For input string: "13-testing+0-builds"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:68)
	at java.base/java.lang.Integer.parseInt(Integer.java:658)
	at java.base/java.lang.Integer.parseInt(Integer.java:776)
	at org.github.jamm.MemoryLayoutSpecification.getEffectiveMemoryLayoutSpecification(MemoryLayoutSpecification.java:190)
	at org.github.jamm.MemoryLayoutSpecification.<clinit>(MemoryLayoutSpecification.java:31)
	... 28 more
```

This does not look like Dacapo problem, exactly, but the fact that Cassandra relies on https://github.com/jbellis/jamm/, which parses the version string and gets confused because of that. Submitting the issue here for the record.

Amusingly, jdk11 build runs cassandra fine, probably because there is a dot in "11.0.4".

**Comment by shipilev** [comment]
I believe it is fixed with https://github.com/jbellis/jamm/commit/c81473ebf3cf41bcc5e7ebfeb3559bc88249a486, but unable to verify here. The fact changeset synopsis says "java 9 support", and Dacapo suite is apparently targeting 11 is interesting: maybe "cassandra" should be updated to get proper support for JDK >=9.
