### ISSUE TITLE
unable to run batik and eclipse with openJDK9

### ISSUE THREAD

**Issue by atpoverload** [dacapobench/dacapobench#175]
I am trying to run batik and eclipse with the open jdk 9 (I am using the dev branch) but I am unable to run either.

When I run batik, I get the following output:
```
===== DaCapo 9.12-MR1 batik starting =====
About to transcode 3 SVG file(s)

Converting mapWaadt.svg to /home/timur/Projects/chappie/run/dacapo/SAMPLE/scratch/mapWaadt.png ... ... success
Converting mapSpain.svg to /home/timur/Projects/chappie/run/dacapo/SAMPLE/scratch/mapSpain.png ... ... success
Converting sydney.svg to /home/timur/Projects/chappie/run/dacapo/SAMPLE/scratch/sydney.png ... java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.dacapo.harness.Batik.iterate(Batik.java:41)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at Harness.main(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: com/sun/image/codec/jpeg/TruncatedFileException
        at org.apache.batik.ext.awt.image.codec.jpeg.JPEGRegistryEntry.handleStream(JPEGRegistryEntry.java:87)
        at org.apache.batik.ext.awt.image.spi.ImageTagRegistry.readURL(ImageTagRegistry.java:189)
        at org.apache.batik.bridge.SVGImageElementBridge.createImageGraphicsNode(SVGImageElementBridge.java:257)
        at org.apache.batik.bridge.SVGImageElementBridge.buildImageGraphicsNode(SVGImageElementBridge.java:176)
        at org.apache.batik.bridge.SVGImageElementBridge.createGraphicsNode(SVGImageElementBridge.java:118)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:206)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
        at org.apache.batik.bridge.GVTBuilder.buildGraphicsNode(GVTBuilder.java:212)
        at org.apache.batik.bridge.GVTBuilder.buildComposite(GVTBuilder.java:164)
        at org.apache.batik.bridge.GVTBuilder.build(GVTBuilder.java:78)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:214)
        at org.apache.batik.transcoder.image.ImageTranscoder.transcode(ImageTranscoder.java:92)
        at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:142)
        at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:159)
        at org.apache.batik.apps.rasterizer.SVGConverter.transcode(SVGConverter.java:992)
        at org.apache.batik.apps.rasterizer.SVGConverter.execute(SVGConverter.java:715)
        at org.apache.batik.apps.rasterizer.Main.execute(Main.java:938)
        ... 13 more
Caused by: java.lang.ClassNotFoundException: com.sun.image.codec.jpeg.TruncatedFileException
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
        at org.dacapo.harness.DacapoClassLoader.loadClass(DacapoClassLoader.java:123)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 30 more
```
I believe this is because the sun libraries aren't available in java 9 so the truncated file exception isn't available. Is there a good solution to this? I've tried registering a new handler for jpeg reading but I am having trouble compiling.

When I run eclipse, I get the following output:
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.dacapo.harness.Eclipse.preIteration(Eclipse.java:54)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:171)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:74)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:368)
        ... 13 more
===== DaCapo 9.12-MR1 eclipse starting =====
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.dacapo.harness.Eclipse.iterate(Eclipse.java:65)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:187)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.reStart(EclipseAppLauncher.java:157)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:370)
        ... 13 more
===== DaCapo 9.12-MR1 eclipse PASSED in 7 msec =====
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.dacapo.harness.Eclipse.postIteration(Eclipse.java:74)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:198)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:199)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:152)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at Harness.main(Unknown Source)
Caused by: java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.reStart(EclipseAppLauncher.java:157)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:370)
        ... 13 more
```
I am not sure what the failure is for eclipse. I looked through the scratch folder and it looks like scratch/eclipse/configuration/org.eclipse.core.runtime is missing. However, if I run it with java 8, org.eclipse.core.runtime is there. Is there any reason why this would be happening in java 9?

thanks!
timur

**Comment by mifisignal** [comment]
See https://www.stichlberger.com/software/workaround-for-batiks-noclassdeffounderrorclassnotfoundexception-truncatedfileexception/

**Comment by amordahl** [comment]
Did anybody ever find a solution to the Eclipse issue? I am also observing that Eclipse works on JDK 8 but not on JDK 11.
