### ISSUE TITLE
graphchi benchmark fails with assertions enabled

### ISSUE THREAD

**Issue by lmesnik** [dacapobench/dacapobench#178]
The graphchi benchmark fails when '-ea' is enabled.

The issue is reproduced with JDK 8 - 13. The workaround is to disable assertion.

java -showversion -ea -jar dacapo-evaluation-git+309e1fa-java8.jar  graphchi
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)
... 
Using scaled threading model. 4 processors detected, 4 threads used to drive the workload, in a possible range of [1,unlimited]
===== DaCapo evaluation-git+309e1fa graphchi starting =====
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.dacapo.harness.GraphChi.iterate(GraphChi.java:39)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:197)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Harness.main(Unknown Source)
Caused by: java.lang.AssertionError
	at edu.cmu.graphchi.preprocessing.FastSharder.processShovel(FastSharder.java:619)
	at edu.cmu.graphchi.preprocessing.FastSharder.process(FastSharder.java:300)
	at edu.cmu.graphchi.preprocessing.FastSharder.shard(FastSharder.java:776)
	at edu.cmu.graphchi.preprocessing.FastSharder.shard(FastSharder.java:787)
	at edu.cmu.graphchi.apps.Pagerank.main(Pagerank.java:101)
	... 13 more

Leonid

**Comment by steveblackburn** [comment]
This has been fixed.  Closing.
