### ISSUE TITLE
Kafka benchmark fails

### ISSUE THREAD

**Issue by vext01** [dacapobench/dacapobench#183]
On the 309e1fa evaluation snapshot on Debian 10, the kafka benchmark fails with a big stacktrace:

On graal without JVMCI:
```
$ ./graalvm-ce-java11-19.3.2/bin/java -jar dacapo-evaluation-git+309e1fa-java8.jar -n 5 kafka
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 4 processors detected, 4 threads used to drive the workload, in a possible range of [1,unlimited]
Starting Zookeeper...
Starting Kafka Server...
[2020-05-18 17:04:42,831] WARN Unable to read additional data from client sessionid 0x0, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
Starting Agent...
Starting Coordinator...
===== DaCapo evaluation-git+309e1fa kafka starting warmup 1 =====
Trogdor is running the benchmark....
[2020-05-18 17:04:46,632] WARN Failed to create or verify topics {foo1=(name=foo1, numPartitions=10, replicationFactor=1, replicasAssignments=null, configs=null), foo2=(name=foo2, numPartitions=10, replicationFactor=1, replicasAssignments=null, configs=null), foo3=(name=foo3, numPartitions=10, replicationFactor=1, replicasAssignments=null, configs=null), foo4=(name=foo4, numPartitions=10, replicationFactor=1, replicasAssignments=null, configs=null), foo5=(name=foo5, numPartitions=10, replicationFactor=1, replicasAssignments=null, configs=null)} (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at org.apache.kafka.trogdor.common.WorkerUtils.verifyTopics(WorkerUtils.java:249)
	at org.apache.kafka.trogdor.common.WorkerUtils.createTopics(WorkerUtils.java:159)
	at org.apache.kafka.trogdor.common.WorkerUtils.createTopics(WorkerUtils.java:131)
	at org.apache.kafka.trogdor.workload.ProduceBenchWorker$Prepare.run(ProduceBenchWorker.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2020-05-18 17:04:46,633] WARN Prepare caught an exception:  (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at org.apache.kafka.trogdor.common.WorkerUtils.verifyTopics(WorkerUtils.java:249)
	at org.apache.kafka.trogdor.common.WorkerUtils.createTopics(WorkerUtils.java:159)
	at org.apache.kafka.trogdor.common.WorkerUtils.createTopics(WorkerUtils.java:131)
	at org.apache.kafka.trogdor.workload.ProduceBenchWorker$Prepare.run(ProduceBenchWorker.java:121)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
[2020-05-18 17:04:47,542] WARN node0: Worker producer0.3615975373936211 finished with error 'org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.' and status '"Creating 5 topic(s)"' (org.apache.kafka.trogdor.coordinator.TaskManager)
Error: org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
Finished
Digest validation failed for stdout.log, expecting 0x95b290c61f52682342b11545840611bdba3ed5b4 found 0xf6b51ff833ff3ab9714529aeb209f0cdb352871c
===== DaCapo evaluation-git+309e1fa kafka FAILED warmup =====
===== DaCapo evaluation-git+309e1fa kafka starting warmup 2 =====
Trogdor is running the benchmark....
Finished
===== DaCapo evaluation-git+309e1fa kafka completed warmup 2 in 5139 msec =====
===== DaCapo evaluation-git+309e1fa kafka starting warmup 3 =====
Trogdor is running the benchmark....
Finished
===== DaCapo evaluation-git+309e1fa kafka completed warmup 3 in 5124 msec =====
===== DaCapo evaluation-git+309e1fa kafka starting warmup 4 =====
Trogdor is running the benchmark....
Finished
===== DaCapo evaluation-git+309e1fa kafka completed warmup 4 in 5120 msec =====
===== DaCapo evaluation-git+309e1fa kafka starting =====
Trogdor is running the benchmark....
Finished
===== DaCapo evaluation-git+309e1fa kafka PASSED in 5119 msec =====
Validation FAILED for kafka default
[2020-05-18 17:05:08,321] WARN Running coordinator shutdown hook. (org.apache.kafka.trogdor.coordinator.Coordinator)
[2020-05-18 17:05:08,321] WARN Running agent shutdown hook. (org.apache.kafka.trogdor.agent.Agent)
Shutdown Agent...
Shutdown Coordinator...
```

On OpenJDK14:
```
$ ./jdk-14.0.1/bin/java -jar dacapo-evaluation-git+309e1fa-java8.jar -n 5 kafka
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 4 processors detected, 4 threads used to drive the workload, in a possible range of [1,unlimited]
Starting Zookeeper...
Starting Kafka Server...
[2020-05-18 17:07:45,393] WARN Unable to read additional data from client sessionid 0x0, likely client has closed socket (org.apache.zookeeper.server.NIOServerCnxn)
[2020-05-18 17:07:45,641] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:46,743] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:47,844] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:48,945] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:50,045] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:51,146] WARN Session 0x0 for server localhost/<unresolved>:2181, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.nio.channels.UnresolvedAddressException
	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
	at java.base/sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:727)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:741)
	at org.apache.zookeeper.ClientCnxnSocketNIO.registerAndConnect(ClientCnxnSocketNIO.java:277)
	at org.apache.zookeeper.ClientCnxnSocketNIO.connect(ClientCnxnSocketNIO.java:287)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1021)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1064)
[2020-05-18 17:07:52,354] ERROR Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer)
kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:242)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at kafka.utils.CoreUtils$.inLock(CoreUtils.scala:251)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:238)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:96)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1825)
	at kafka.server.KafkaServer.createZkClient$1(KafkaServer.scala:361)
	at kafka.server.KafkaServer.initZkClient(KafkaServer.scala:385)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:205)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:38)
	at kafka.Kafka$.main(Kafka.scala:75)
	at kafka.Kafka.main(Kafka.scala)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.dacapo.kafka.ServerStarter$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:832)
[2020-05-18 17:07:52,360] ERROR Exiting Kafka. (kafka.server.KafkaServerStartable)
```

**Comment by vext01** [comment]
Interestingly, after updating our Java VMs and implementing a timeout feature in our benchmark runner, this benchmark is now timing out (this time we allowed each benchmark run 3.75 hours). We observed this is on hotspot, graal and openj9 using 750 iterations.

Not sure if that helps much, but thought you may like to know :)

Thanks!

**Comment by steveblackburn** [comment]
750 is a lot of iterations!  TBH I have not been testing them in such a configuration.

I assume you're using the default collector (G1)?  It would be interesting to see whether this problem still exists.  All of the benchmarks have been upgraded since you made this report.
