### ISSUE TITLE
Tradesoap and Tradebeans Error

### ISSUE THREAD

**Issue by skrlin** [dacapobench/dacapobench#189]
java version: 
```
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```
os version：
`Ubuntu18.04-server`

when we run the tradesoap and tradebeans ，we find the following errors:
```
dacapo test set
Error initializing DaCapo: (404)Not Found
AxisFault
 faultCode: {http://xml.apache.org/axis/}HTTP
 faultSubcode: 
 faultString: (404)Not Found
 faultActor: 
 faultNode: 
 faultDetail: 
	{}:return code:  404
&lt;html&gt;
&lt;head&gt;
&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=ISO-8859-1&quot;/&gt;
&lt;title&gt;Error 404 NOT_FOUND&lt;/title&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;h2&gt;HTTP ERROR: 404&lt;/h2&gt;&lt;pre&gt;NOT_FOUND&lt;/pre&gt;
&lt;p&gt;RequestURI=/daytrader/services/TradeWSServices&lt;/p&gt;
&lt;p&gt;&lt;i&gt;&lt;small&gt;&lt;a href=&quot;http://jetty.mortbay.org&quot;&gt;Powered by jetty://&lt;/a&gt;&lt;/small&gt;&lt;/i&gt;&lt;/p&gt;
                                                
                                    
&lt;/body&gt;
&lt;/html&gt;

	{http://xml.apache.org/axis/}HttpErrorCode:404

(404)Not Found
	at org.apache.axis.transport.http.HTTPSender.readFromSocket(HTTPSender.java:744)
	at org.apache.axis.transport.http.HTTPSender.invoke(HTTPSender.java:144)
	at org.apache.axis.strategies.InvocationStrategy.visit(InvocationStrategy.java:32)
	at org.apache.axis.SimpleChain.doVisiting(SimpleChain.java:118)
	at org.apache.axis.SimpleChain.invoke(SimpleChain.java:83)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:165)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at org.apache.geronimo.axis.client.ServiceEndpointMethodInterceptor.doIntercept(ServiceEndpointMethodInterceptor.java:103)
	at org.apache.geronimo.axis.client.ServiceEndpointMethodInterceptor.intercept(ServiceEndpointMethodInterceptor.java:58)
	at org.apache.geronimo.axis.client.GenericServiceEndpointWrapper$$EnhancerByCGLIB$$e6c74a27.initializeDaCapo(<generated>)
	at org.apache.geronimo.samples.daytrader.soap.TradeWebSoapProxy.initializeDaCapo(TradeWebSoapProxy.java:280)
	at org.apache.geronimo.samples.daytrader.dacapo.DaCapoTrader$1.run(DaCapoTrader.java:187)
	at java.lang.Thread.run(Thread.java:748)
```
If someone could help me out with this problem, we would be very grateful

**Comment by gilles-duboscq** [comment]
We've also seen this intermittently on tradebeans while testing various JDK version (8, 11, 17).

**Comment by steveblackburn** [comment]
This appears to have been fixed as a side effect of the upgrade to wildfly.

One explanation for such failures may be that server threads encounter OOMs but don't shut the process down, so clients continue to try to run, but the server has failed.

You can mitigate this by running with `-XX:FailOnOutOfMemoryError`, which will force the JVM to terminate when any thread OOMs.
