### ISSUE TITLE
cassandra failed with IllegalAccessException on evaluation-git-f480064

### ISSUE THREAD

**Issue by caizixian** [dacapobench/dacapobench#211]
```console
$ /usr/lib/jvm/temurin-11-jdk-amd64/bin/java  -Xms888M -Xmx888M -cp /usr/share/benchmarks/dacapo/dacapo-evaluation-git-f480064.jar Harness  -n 5 -s default cassandra
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,unlimited]
Cassandra starting...
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.dacapo.harness.Cassandra.prepare(Cassandra.java:124)
    at org.dacapo.harness.Benchmark.run(Benchmark.java:205)
    at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
    at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at Harness.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
    at org.apache.cassandra.config.DatabaseDescriptor.guessFileStore(DatabaseDescriptor.java:1193)
    at org.apache.cassandra.config.DatabaseDescriptor.applySimpleConfig(DatabaseDescriptor.java:550)
    at org.apache.cassandra.config.DatabaseDescriptor.applyAll(DatabaseDescriptor.java:350)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:178)
    at org.apache.cassandra.config.DatabaseDescriptor.daemonInitialization(DatabaseDescriptor.java:162)
    at org.apache.cassandra.service.CassandraDaemon.applyConfig(CassandraDaemon.java:816)
    at org.apache.cassandra.service.EmbeddedCassandraService.start(EmbeddedCassandraService.java:49)
    ... 13 more
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@78fbff54/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @158da8e)
    at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:107)
    ... 20 more
Caused by: java.lang.IllegalAccessException: access to public member failed: jdk.internal.ref.Cleaner.clean[Ljava.lang.Object;@78fbff54/invokeVirtual, from org.apache.cassandra.io.util.FileUtils (unnamed module @158da8e)
    at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:942)
    at java.base/java.lang.invoke.MethodHandles$Lookup.checkAccess(MethodHandles.java:2201)
    at java.base/java.lang.invoke.MethodHandles$Lookup.checkMethod(MethodHandles.java:2141)
    at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodCommon(MethodHandles.java:2285)
    at java.base/java.lang.invoke.MethodHandles$Lookup.getDirectMethodNoSecurityManager(MethodHandles.java:2278)
    at java.base/java.lang.invoke.MethodHandles$Lookup.unreflect(MethodHandles.java:1747)
    at org.apache.cassandra.io.util.FileUtils.<clinit>(FileUtils.java:96)
```

Note that this doesn't happen when running with the jar directly `/usr/lib/jvm/temurin-11-jdk-amd64/bin/java  -Xms888M -Xmx888M -jar /usr/share/benchmarks/dacapo/dacapo-evaluation-git-f480064.jar  -n 5 -s default cassandra`.

This also doesn't happen on evaluation-git-29a657f.

Presumably this might have something to do with the cassandra version bump in https://github.com/dacapobench/dacapobench/commit/a822e6998f86f99485a415eb3931b9fa2cde05d0

**Comment by steveblackburn** [comment]
Fixed.
