### ISSUE TITLE
tomcat xlong failure for evaluation-git-29a657f

### ISSUE THREAD

**Issue by heshpdx** [dacapobench/dacapobench#215]
I am running on an Ampere Altra QS-80 with two sockets. I think 160 threads might be too many for xlong to handle? Or just the number of transactions is too much for the buffer. is the fix to just increase the size of the buffer?

```
$ ../JAVA/ms-jdk-11.0.13+8/bin/java -jar ../DACAPO/dacapo-evaluation-git-29a657f.jar -n 10 -v -s xlong tomcat

Class name: org.dacapo.harness.Tomcat
Configurations:
short     Tomcat servlet container
long      Runs the tomcat sample web applications
author    Apache Software Foundation
license   Apache License, Version 2.0
copyright Copyright (c) Apache Software Foundation
url       http://tomcat.apache.org
version   9.0.37
sizes     default large small xlong
Using scaled threading model. 160 processors detected, 160 threads used to drive the workload, in a possible range of [1,16384]
Server thread created
===== DaCapo evaluation-git-29a657f tomcat starting warmup 1 =====
Loading web application
Creating client threads to issue 800000 rounds of 41 requests (32800000).
Too many transactions. 32800000 > LATENCY_BUFFER_SIZE (10000000)
java.lang.Exception: Stack trace
        at java.base/java.lang.Thread.dumpStack(Thread.java:1383)
        at org.dacapo.harness.LatencyReporter.initialize(LatencyReporter.java:62)
        at org.dacapo.harness.LatencyReporter.initialize(LatencyReporter.java:55)
        at org.dacapo.harness.Tomcat.iterate(Tomcat.java:171)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:221)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by steveblackburn** [comment]
Yes. Sorry for that.  The xlong option is depricated.  You should find that all of the available sizes work fine now (for tomcat it is just small, default and large; some benchmarks have vlarge).
