### ISSUE TITLE
Kafka doesn't quit cleanly (deadlock?) when running with a single hardware thread

### ISSUE THREAD

**Issue by caizixian** [dacapobench/dacapobench#254]
```
taskset -c 0 java  -Xms388M -Xmx388M -jar /usr/share/benchmarks/dacapo/dacapo-23.11-chopin.jar kafka
Using scaled threading model. 1 processors detected, 1 threads used to drive the workload, in a possible range of [1,unlimited]
Version: kafka 3.3.1 (use -p to print nominal benchmark stats)
Starting Zookeeper...
Starting Kafka Server...
===== DaCapo 23.11-chopin kafka starting =====
Trogdor is running the workload....
Starting 1000000 requests...
10%^CCompleted requests
[2024-02-20 10:07:08,711] ERROR Exception on final future (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1343)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
	at org.apache.kafka.clients.producer.internals.ProduceRequestResult.await(ProduceRequestResult.java:76)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:62)
	at org.apache.kafka.clients.producer.internals.FutureRecordMetadata.get(FutureRecordMetadata.java:30)
	at org.apache.kafka.trogdor.workload.ProduceBenchWorker$SendRecords.call(ProduceBenchWorker.java:333)
	at org.apache.kafka.trogdor.workload.ProduceBenchWorker$SendRecords.call(ProduceBenchWorker.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

```
java  -Xms388M -Xmx388M -jar /usr/share/benchmarks/dacapo/dacapo-23.11-chopin.jar kafka
Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,unlimited]
Version: kafka 3.3.1 (use -p to print nominal benchmark stats)
Starting Zookeeper...
Starting Kafka Server...
===== DaCapo 23.11-chopin kafka starting =====
Trogdor is running the workload....
Starting 1000000 requests...
15%^CCompleted requests
Finished
Digest validation failed for stdout.log, expecting 0xd054f76402d83d91bc9824746d89c489c458a103 found 0x261ea9f1ceb590ae9049e936c30331e8507ee42e
===== DaCapo 23.11-chopin kafka FAILED =====
===== DaCapo simple tail latency: 50% 0 usec, 90% 22252 usec, 99% 157052 usec, 99.9% 168037 usec, 99.99% 169040 usec, max 169290 usec, measured over 1000000 events =====
===== DaCapo metered tail latency: 50% 0 usec, 90% 24098 usec, 99% 157052 usec, 99.9% 168037 usec, 99.99% 169040 usec, max 169290 usec, measured over 1000000 events =====
Validation FAILED for kafka default
```

**Comment by caizixian** [comment]
Sometimes it recovers after a while
```
rg.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,589] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,589] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
[2024-02-20 21:05:06,590] ERROR SendRecordsCallback: error (org.apache.kafka.trogdor.workload.ProduceBenchWorker)
org.apache.kafka.common.errors.TimeoutException: Expiring 31 record(s) for dacapo-1-9:120900 ms has passed since batch creation
Finished
Digest validation failed for stdout.log, expecting 0xd054f76402d83d91bc9824746d89c489c458a103 found 0xac3f178b6023ec3bd624877e3abaae045f83ec69
===== DaCapo 23.11-chopin kafka FAILED warmup =====
```

**Comment by caizixian** [comment]
There have also been cases where all iterations of the benchmark run to completion, but the VM never terminates after extended waiting (2.5hrs)
