### ISSUE TITLE
The benchmark kafka got an 'InvocationTargetException' 

### ISSUE THREAD

**Issue by Xuefeng-2000** [dacapobench/dacapobench#281]
My JDK is java 11.0.22 2024-01-16 LTS. I got an 'InvocationTargetException' when I ran Kafka. How can I solve this exception?

`root@a100:/dacapobench/benchmarks# java -jar dacapo-evaluation-git-b281fb21.jar -c ExampleCallback kafka
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 256 processors detected, 256 threads used to drive the workload, in a possible range of [1,unlimited]
Version: kafka 3.3.1 (use -p to print nominal benchmark stats)
java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.dacapo.harness.Kafka.prepare(Kafka.java:46)
        at org.dacapo.harness.Benchmark.run(Benchmark.java:229)
        at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
        at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at Harness.main(Harness.java:39)
Caused by: java.lang.ClassNotFoundException: org.apache.zookeeper.server.ZooKeeperServerMain
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at org.dacapo.harness.DacapoClassLoader.loadClass(DacapoClassLoader.java:152)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.dacapo.kafka.ZookeeperStarter.<init>(Unknown Source)
        at org.dacapo.kafka.Launcher.launching(Unknown Source)
        ... 13 more`

**Comment by steveblackburn** [comment]
I'm not sure what's going on here.  Is there a reason you're not using a release build?  I suggest you see if this is issue arrises on a release build before pursing this further.

**Comment by steveblackburn** [comment]
I have tried to reproduce this, but cannot.  Please feel free to reopen if you have more specific information.

```
$ java -jar dacapo-evaluation-git-b281fb21.jar -c ExampleCallback kafka
--------------------------------------------------------------------------------
IMPORTANT NOTICE:  This is NOT a release build of the DaCapo suite.
Since it is not an official release of the DaCapo suite, care must be taken when
using the suite, and any use of the build must be sure to note that it is not an
offical release, and should note the relevant git hash.

Feedback is greatly appreciated.   The preferred mode of feedback is via github.
Please use our github page to create an issue or a pull request.
    https://github.com/dacapobench/dacapobench.
--------------------------------------------------------------------------------

Using scaled threading model. 24 processors detected, 24 threads used to drive the workload, in a possible range of [1,unlimited]
Version: kafka 3.3.1 (use -p to print nominal benchmark stats)
Starting Zookeeper...
Starting Kafka Server...
Example callback starting kafka
===== DaCapo evaluation-git-b281fb21 kafka starting =====
Trogdor is running the workload....
Starting 1000000 requests...
100%
Completed requests
Finished
Example callback stopping 
===== DaCapo evaluation-git-b281fb21 kafka PASSED in 6683 msec =====
Example callback PASSED kafka, observed 1000000 requests
===== DaCapo processed 1000000 requests in 5284 msec, 189250 requests per second =====
===== DaCapo simple tail latency: 50% 17221 usec, 90% 54859 usec, 99% 329900 usec, 99.9% 339911 usec, 99.99% 342694 usec, max 344178 usec, measured over 1000000 events =====
===== DaCapo metered tail latency: 50% 157837 usec, 90% 313883 usec, 99% 345952 usec, 99.9% 348139 usec, 99.99% 349177 usec, max 349614 usec, measured over 1000000 events =====
```
