### ISSUE TITLE
h2o build issues

### ISSUE THREAD

**Issue by steveblackburn** [dacapobench/dacapobench#296]
The h2o build process is brittle and nondeterministic.   For example, a checkout and rebuild of the last DaCapo release yields a h2o that no longer works on jdk8, despite the h2o sources being unchanged.

**Comment by caizixian** [comment]
https://github.com/h2oai/h2o-3/pull/16355

**Comment by steveblackburn** [comment]
After some debugging by @caizixian, we now know the following:

1. The failure to run with JDK 8 is because we're now building h2o with JDK 11 (#259).  Because we build with 11, it generates class files that will fail with 8.
2. The root cause of #259 seems to be related to gradle.
   * If the gradle daemon is already running and is using JDK11, then it will have the effect of building h2o with JDK 11.
   * This is a known gradle problem:
      * https://stackoverflow.com/questions/73633278/gradle-keeps-using-wrong-java-version
      * https://stackoverflow.com/questions/54189630/kill-all-gradle-daemons-regardless-version
      
 So it seems that we want to revert 89aaec1 and fix the root cause issue relating to gradle.

**Comment by caizixian** [comment]
Perhaps we should backport this fix from upstream https://github.com/h2oai/h2o-3/pull/16359

**Comment by steveblackburn** [comment]
Frustratingly, reverting https://github.com/dacapobench/dacapobench/commit/89aaec1a72663328466fece222e5630ee939768b does not address the issue.

At build time, h2o will crash executing the following:

```
8.0.322-tem//bin/java -Xmx4g -ea -Dsys.ai.h2o.ext.rest.toggle.XGBoost=true -Dsys.ai.h2o.ext.core.toggle.XGBoost=true -Dsys.ai.h2o.ext.core.toggle.KrbStandalone=false -cp dacapobench/benchmarks/bms/h2o/build/h2o-assemblies/main/build/libs/main-3.42.0.jar water.H2OApp -name H2O_runit_steveblackburn_9103383 -baseport 48000 -ip 127.0.0.1
```
with the stack trace:

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
        at water.TimeLine.record1(TimeLine.java:99) [main-3.42.0.jar:?]
        at water.TimeLine.record_send(TimeLine.java:110) [main-3.42.0.jar:?]
        at water.AutoBuffer.udpSend(AutoBuffer.java:575) [main-3.42.0.jar:?]
        at water.AutoBuffer.close(AutoBuffer.java:441) [main-3.42.0.jar:?]
        at water.UDPRebooted$T.send(UDPRebooted.java:41) [main-3.42.0.jar:?]
        at water.UDPRebooted$T.broadcast(UDPRebooted.java:43) [main-3.42.0.jar:?]
        at water.H2O.startNetworkServices(H2O.java:1939) [main-3.42.0.jar:?]
        at water.H2O.main(H2O.java:2477) [main-3.42.0.jar:?]
        at water.H2OStarter.start(H2OStarter.java:22) [main-3.42.0.jar:?]
        at water.H2OStarter.start(H2OStarter.java:48) [main-3.42.0.jar:?]
        at water.H2OApp.main(H2OApp.java:12) [main-3.42.0.jar:?]
Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
        at water.AutoBuffer.udpSend(AutoBuffer.java:578)
        at water.AutoBuffer.close(AutoBuffer.java:441)
        at water.UDPRebooted$T.send(UDPRebooted.java:41)
        at water.UDPRebooted$T.broadcast(UDPRebooted.java:43)
        at water.H2O.startNetworkServices(H2O.java:1939)
        at water.H2O.main(H2O.java:2477)
        at water.H2OStarter.start(H2OStarter.java:22)
        at water.H2OStarter.start(H2OStarter.java:48)
        at water.H2OApp.main(H2OApp.java:12)
```

However, the respective classes _are_ compiled to 1.8 (major 52):

```
Classfile tmp/water/TimeLine.class
  Last modified Aug 13, 2024; size 7997 bytes
  SHA-256 checksum bc77b179211c9ff7d0f105fb952f6e7ef8a0aa8b0f1c4fa8d2ca2e4298a4549f
  Compiled from "TimeLine.java"
public class water.TimeLine extends water.UDP
  minor version: 0
  major version: 52
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #2                          // water/TimeLine
  super_class: #4                         // water/UDP
  interfaces: 0, fields: 11, methods: 27, attributes: 2
```

```
Classfile  tmp/water/AutoBuffer.class
  Last modified Aug 13, 2024; size 58767 bytes
  SHA-256 checksum a7559126cdd72b61f05bac6599debc7ac5df82bba1f5800d22a8b8ce1b841738
  Compiled from "AutoBuffer.java"
public final class water.AutoBuffer implements java.lang.AutoCloseable
  minor version: 0
  major version: 52
  flags: (0x0031) ACC_PUBLIC, ACC_FINAL, ACC_SUPER
  this_class: #2                          // water/AutoBuffer
  super_class: #4                         // java/lang/Object
  interfaces: 1, fields: 29, methods: 228, attributes: 2
```

So it seems we're building _and_ running with 1.8.  

Furthermore, `java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer` and `java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer` are both members of [java.nio.Buffer](https://docs.oracle.com/javase/8/docs/api/java/nio/Buffer.html) for JDK8.

This isn't making sense.

Another confounding factor is that we've successfully built from the same githash (eg the latest release, https://github.com/dacapobench/dacapobench/commit/fd292e92f8c40495a6ca05ff3b8a77c6c4265606) and produced  a build on which jdk8 can run h2o, but we can no longer create such a build for that same githash.

**Comment by steveblackburn** [comment]
The problem is trivially resolved by setting the CLASSPATH environment variable to point to JDK8 at build time.
