### ISSUE TITLE
Intermittent NullPointerException from the spring benchmark

### ISSUE THREAD

**Issue by Peter-B-Kessler** [dacapobench/dacapobench#302]
I occasionally get a NullPointerException from the spring benchmark:

 $ ${JAVA_HOME}/OpenJDK/jdk-22.0.2/bin/java -showversion -jar ${DACAPO_HOME}/dacapo-23.11-chopin.jar --iterations 5 --size default spring
...
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "<local2>[0]" is null
	at org.h2.util.StringUtils.toUpperEnglish(StringUtils.java:90) ~[h2-2.1.214.jar!/:na]
        ...

Different failures have different stack traces, but they always start with the failure at org.h2.util.StringUtils.toUpperEnglish(StringUtils.java:90).  If you want, I can send you the complete unique stack traces I have seen: 6 so far.

I am running on an Ampere Altra, and I happen to be testing with `numactl` to use sets of 20 adjacent cores, but I have seen the NullPointerException on each of 0-19, 20-39, 40-59, and 60-79, so I don't think it is core-related.

**Comment by steveblackburn** [comment]
This has echos of https://github.com/dacapobench/dacapobench/issues/227 and the fix https://github.com/dacapobench/dacapobench/commit/dc6c6b68ca7a2b12f75f1cd8a64678eaf4945e22

**Comment by ericcaspole** [comment]
This problem is happening because of the unsynchronized cache in h2 at this line

https://github.com/h2database/h2database/blob/version-2.1.214/h2/src/main/org/h2/util/StringUtils.java#L90

Racing with the cache loading lines around

https://github.com/h2database/h2database/blob/version-2.1.214/h2/src/main/org/h2/util/StringUtils.java#L95

And the benchmark selects to run with the number of cores -

"Using scaled threading model. 8 processors detected, 8 threads used to drive the workload, in a possible range of [1,unlimited]"

Since there is no synchronization there is some chance the statements in the loading steps could be reordered by the hardware.
I am not a JMM expert but we only observe this problem on some ARM cores, and at least for me, never on Intel. We could repro the exception in a much simpler example that operated like this situation.

Also, it looks like this cache exists in the same way in the latest version of h2:

https://github.com/h2database/h2database/blob/version-2.3.232/h2/src/main/org/h2/util/StringUtils.java#L93



Whole stack trace:

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "<local2>[0]" is null
	at org.h2.util.StringUtils.toUpperEnglish(StringUtils.java:90) ~[h2-2.1.214.jar!/:na]
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3466) ~[h2-2.1.214.jar!/:na]
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:337) ~[h2-2.1.214.jar!/:na]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java) ~[HikariCP-4.0.3.jar!/:na]
	at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$2.doExtract(IntegerTypeDescriptor.java:62) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:243) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.type.AbstractStandardBasicType.hydrate(AbstractStandardBasicType.java:329) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.readIdentifierHydratedState(EntityReferenceInitializerImpl.java:106) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.process.internal.EntityReferenceInitializerImpl.hydrateIdentifier(EntityReferenceInitializerImpl.java:85) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.process.internal.AbstractRowReader.readRow(AbstractRowReader.java:68) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractRows(ResultSetProcessorImpl.java:157) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.process.internal.ResultSetProcessorImpl.extractResults(ResultSetProcessorImpl.java:94) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.plan.exec.internal.AbstractLoadPlanBasedLoader.executeLoad(AbstractLoadPlanBasedLoader.java:105) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.collection.plan.AbstractLoadPlanBasedCollectionInitializer.initialize(AbstractLoadPlanBasedCollectionInitializer.java:87) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:705) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:76) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:2208) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection$4.doWork(AbstractPersistentCollection.java:595) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:264) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:591) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.collection.internal.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:787) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1001) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:987) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:362) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2868) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2850) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2677) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1459) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665) ~[hibernate-core-5.6.10.Final.jar!/:5.6.10.Final]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:198) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:156) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:144) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.7.2.jar!/:2.7.2]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.7.2.jar!/:2.7.2]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:160) ~[spring-data-commons-2.7.2.jar!/:2.7.2]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139) ~[spring-data-commons-2.7.2.jar!/:2.7.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.22.jar!/:5.3.22]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.22.jar!/:5.3.22]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.22.jar!/:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.22.jar!/:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145) ~[spring-data-jpa-2.7.2.jar!/:2.7.2]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.22.jar!/:5.3.22]
	at jdk.proxy2/jdk.proxy2.$Proxy143.findById(Unknown Source) ~[na:na]
	at org.springframework.samples.petclinic.owner.OwnerController.findOwner(OwnerController.java:60) ~[classes!/:2.7.3]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:573) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.method.annotation.ModelFactory.invokeModelAttributeMethods(ModelFactory.java:143) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.method.annotation.ModelFactory.initModel(ModelFactory.java:112) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:872) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1070) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.web.servlet.resource.ResourceUrlEncodingFilter.doFilter(ResourceUrlEncodingFilter.java:67) ~[spring-webmvc-5.3.22.jar!/:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96) ~[spring-boot-actuator-2.7.3.jar!/:2.7.3]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117) ~[spring-web-5.3.22.jar!/:5.3.22]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1789) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.65.jar!/:na]
	at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]

**Comment by caizixian** [comment]
> This problem is happening because of the unsynchronized cache in h2 at this line

@ericcaspole thanks for investigating this. I'm not very familiar with the Java memory model. Is it correct that without using Atomic, the compiler is free to rewrite the code into, for example,
```java
    public static String toUpperEnglish(String s) {
        if (s.length() > TO_UPPER_CACHE_MAX_ENTRY_LENGTH) {
            return s.toUpperCase(Locale.ENGLISH);
        }
        int index = s.hashCode() & (TO_UPPER_CACHE_LENGTH - 1);
        String[] e = TO_UPPER_CACHE[index];
        if (e != null) {
            if (e[0].equals(s)) {
                return e[1];
            }
        }
        String s2 = s.toUpperCase(Locale.ENGLISH);
        TO_UPPER_CACHE[index] = new String[2];
        TO_UPPER_CACHE[index][0] = s;
        TO_UPPER_CACHE[index][1] = s2;
        return s2;
    }
```

which could result in `e != null` but `e[0] == null`.

**Comment by Peter-B-Kessler** [comment]
I got one failure in 1000 repetitions of the spring benchmark with your dacapo-evaluation-git-06c3cf33.jar.

The failure is similar to, but not the same as, the previous failure.  Maybe you fixed one failure and you are on the next one.  I have attached the log of the failing run.  

[dacapo-evaluation-git-06c3cf33-failure.txt](https://github.com/user-attachments/files/17171628/dacapo-evaluation-git-06c3cf33-failure.txt)

Note that I am running with `--iterations 2`, because I noticed that the failure(s) always happen in the first warmup iteration.  That might be because once the first iteration finishes successfully, the data structure you need is well-formed.  Or it might indicate that the issue is in the complex early part of running an application on the Java virtual machine.  I can't tell how long the spring benchmark has been running at the point of the exception, because the benchmark keeps running and "fails late" after 16.76 seconds.

I am willing to run new versions of DaCapo on Ampere Altra (80 core aarch64) machines, if that will help.

**Comment by steveblackburn** [comment]
Hi @Peter-B-Kessler, it looks like you've tripped on a _different_ upstream bug.

To re-cap, your characterization of this issue (#302) was:

> Different failures have different stack traces, but they always start with the failure at `org.h2.util.StringUtils.toUpperEnglish(StringUtils.java:90`

@ericcaspole diagnosed this and @caizixian pointed out that it was also likely the root cause of #230.  @ericcaspole fixed `h2` bug and submitted an [upstream fix](https://github.com/h2database/h2database/issues/4124), which I integrated into DaCapo in #309.

The error log you posted  [above](https://github.com/dacapobench/dacapobench/issues/302#issuecomment-2380311885) includes a different top of stack:

```
java.lang.NullPointerException: Cannot read the array length because "a" is null
	at java.base/java.util.Arrays.fill(Arrays.java:3181) ~[na:na]
	at org.thymeleaf.context.WebEngineContext$RequestAttributesVariablesMap.<init>(WebEngineContext.java:668) ~[thymeleaf-3.0.15.RELEASE.jar!/:3.0.15.RELEASE]
	at org.thymeleaf.context.WebEngineContext.<init>(WebEngineContext.java:144) ~[thymeleaf-
```

I've created an issue for this new bug (#311).

I'd like to wait until you're able to confirm that you no longer see any evidence of  the `h2` bug before I close this issue.

**Comment by Peter-B-Kessler** [comment]
I have run DaCapo-23.11-MR1-RC1-chopin on an Ampere Altra (aarch64), using OpenJDK/jdk-23.0.1.

I did not find any issues with the DaCapo code.  Good job!

For the record, I had to make the following benchmark-specific modifications to my command lines:

- For cassandra, I needed `-Djava.security.manager=allow`.
- For h2o, I needed `-Dsys.ai.h2o.debug.allowJavaVersions=23`.
- For tradebeans and tradesoap, I needed to use OpenJDK/jdk-17.0.9+9, instead of OpenJDK/jdk-23.0.1.

Probably none of those is a surprise to you.  There are fewer of these exceptions than there were with the previous release candidate.

I did have some trouble (<1%) with the spring benchmark because of [https://bugs.openjdk.org/browse/JDK-8339349](https://bugs.openjdk.org/browse/JDK-8339349), but that is not your issue.  Thank you for exposing it!  @ericcaspole is looking into that from the JDK side.

Since I was running the benchmarks a lot, I gathered the reported times into a chart:

![image](https://github.com/user-attachments/assets/8294341e-cb5f-4f36-beb5-dff174398890)

showing how quickly the various benchmarks warm up.  Or in the case of h2o, showing how the performance degrades.  (I had to remove the absolute time scale from the chart, because I am not allowed to publish performance numbers from an Ampere Altra.  But you get the idea.)

I find that avrora either starts out running well and continues to run well, or it starts out running poorly and never recovers.  I don't know if you consider than an issue.  Some of the other benchmarks (e.g., sunflow) seem to oscillate within a set of iterations: enough to report, but not enough to worry about.  Do not believe people who report a single number for a benchmark without justifying that the number is representative.
