### ISSUE TITLE
Security managers, (Cassandra) can't run with one, can't run without one

### ISSUE THREAD

**Issue by earthling-amzn** [dacapobench/dacapobench#331]
Without explicitly enabling a security manager with `-Djava.security.manager=allow`, the `cassandra` benchmark fails with:
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at org.dacapo.harness.Cassandra.prepare(Cassandra.java:103)
	at org.dacapo.harness.Benchmark.run(Benchmark.java:229)
	at org.dacapo.harness.TestHarness.runBenchmark(TestHarness.java:225)
	at org.dacapo.harness.TestHarness.main(TestHarness.java:170)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:565)
	at Harness.main(Unknown Source)
Caused by: java.lang.ExceptionInInitializerError
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:254)
	at org.apache.cassandra.service.CassandraDaemon.init(CassandraDaemon.java:670)
	at org.apache.cassandra.service.EmbeddedCassandraService.start(EmbeddedCassandraService.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 8 more
Caused by: java.lang.UnsupportedOperationException: Setting a system-wide Policy object is not supported
	at java.base/java.security.Policy.setPolicy(Policy.java:114)
	at org.apache.cassandra.security.ThreadAwareSecurityManager.<clinit>(ThreadAwareSecurityManager.java:114)
	... 12 more
```
Unfortunately, changes to [permanently disable the security manager](https://openjdk.org/jeps/486) have recently been committed to openjdk's tip, so that `-Djava.security.manager=allow` now prevents `cassandra` from running:
```
Error occurred during initialization of VM
java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.
	at java.lang.System.initPhase3(java.base/System.java:2070)
```
Perhaps there is some way to change this requirement in `cassandra`?

**Comment by steveblackburn** [comment]
Thanks for this.

Unfortunately this is a problem with the upstream, cassandra.  I don't think there's a lot we (DaCapo) can do about this, so until they have a fix, we're stuck.  Right?
